/**
 * 錯誤代碼常數定義
 * 提供統一的錯誤代碼管理
 */

export const ERROR_CODES = {
  // 基礎錯誤代碼
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 驗證錯誤代碼
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_NUMBER: 'INVALID_NUMBER',
  INVALID_RANGE: 'INVALID_RANGE',
  DUPLICATE_VALUE: 'DUPLICATE_VALUE',
  FIELD_TOO_SHORT: 'FIELD_TOO_SHORT',
  FIELD_TOO_LONG: 'FIELD_TOO_LONG',
  VALUE_TOO_SMALL: 'VALUE_TOO_SMALL',
  VALUE_TOO_LARGE: 'VALUE_TOO_LARGE',

  // 資源不存在錯誤代碼
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  PRINCIPAL_NOT_FOUND: 'PRINCIPAL_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',

  // 應用程式錯誤代碼
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
  OPERATION_FAILED: 'OPERATION_FAILED',
  CREATE_FAILED: 'CREATE_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  SAVE_FAILED: 'SAVE_FAILED',
  LOAD_FAILED: 'LOAD_FAILED',
  SEARCH_FAILED: 'SEARCH_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  PROCESS_FAILED: 'PROCESS_FAILED',
  INVALID_STATE: 'INVALID_STATE',
  CONCURRENCY_CONFLICT: 'CONCURRENCY_CONFLICT',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // 儲存庫錯誤代碼
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  QUERY_ERROR: 'QUERY_ERROR',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  DATA_INTEGRITY_ERROR: 'DATA_INTEGRITY_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',

  // 認證錯誤代碼
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  PASSWORD_CHANGE_FAILED: 'PASSWORD_CHANGE_FAILED',
  ACCOUNT_NOT_EXISTS: 'ACCOUNT_NOT_EXISTS',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_FAILED: 'TWO_FACTOR_FAILED',
  OAUTH_FAILED: 'OAUTH_FAILED',

  // 網路錯誤代碼
  NETWORK_ERROR: 'NETWORK_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  OFFLINE_ERROR: 'OFFLINE_ERROR',
  CORS_ERROR: 'CORS_ERROR',
  SSL_ERROR: 'SSL_ERROR',
  DNS_ERROR: 'DNS_ERROR',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // HTTP 狀態碼對應的錯誤代碼
  BAD_REQUEST: 'BAD_REQUEST', // 400
  UNAUTHORIZED: 'UNAUTHORIZED', // 401
  FORBIDDEN: 'FORBIDDEN', // 403
  NOT_FOUND_HTTP: 'NOT_FOUND_HTTP', // 404
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED', // 405
  REQUEST_TIMEOUT_HTTP: 'REQUEST_TIMEOUT_HTTP', // 408
  CONFLICT: 'CONFLICT', // 409
  GONE: 'GONE', // 410
  PAYLOAD_TOO_LARGE_HTTP: 'PAYLOAD_TOO_LARGE_HTTP', // 413
  URI_TOO_LONG: 'URI_TOO_LONG', // 414
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE', // 415
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY', // 422
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS', // 429
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // 500
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED', // 501
  BAD_GATEWAY: 'BAD_GATEWAY', // 502
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE', // 503
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT', // 504
  HTTP_VERSION_NOT_SUPPORTED: 'HTTP_VERSION_NOT_SUPPORTED', // 505

  // 業務特定錯誤代碼
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  ACCOUNT_FROZEN: 'ACCOUNT_FROZEN',
  TRANSACTION_LIMIT_EXCEEDED: 'TRANSACTION_LIMIT_EXCEEDED',
  INVALID_TRANSACTION_TYPE: 'INVALID_TRANSACTION_TYPE',
  INVALID_TRANSACTION_STATUS: 'INVALID_TRANSACTION_STATUS',
  TRANSACTION_ALREADY_PROCESSED: 'TRANSACTION_ALREADY_PROCESSED',
  CONTRACT_EXPIRED: 'CONTRACT_EXPIRED',
  CONTRACT_NOT_ACTIVE: 'CONTRACT_NOT_ACTIVE',
  CONTRACT_ALREADY_SIGNED: 'CONTRACT_ALREADY_SIGNED',
  CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',
  PRINCIPAL_INACTIVE: 'PRINCIPAL_INACTIVE',
  DOCUMENT_LOCKED: 'DOCUMENT_LOCKED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',

  // 系統錯誤代碼
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  SERVICE_UNAVAILABLE_ERROR: 'SERVICE_UNAVAILABLE_ERROR',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  RESOURCE_EXHAUSTED: 'RESOURCE_EXHAUSTED',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP 狀態碼對應的錯誤代碼映射
 */
export const HTTP_STATUS_TO_ERROR_CODE: Record<number, ErrorCode> = {
  400: ERROR_CODES.BAD_REQUEST,
  401: ERROR_CODES.UNAUTHORIZED,
  403: ERROR_CODES.FORBIDDEN,
  404: ERROR_CODES.NOT_FOUND_HTTP,
  405: ERROR_CODES.METHOD_NOT_ALLOWED,
  408: ERROR_CODES.REQUEST_TIMEOUT_HTTP,
  409: ERROR_CODES.CONFLICT,
  410: ERROR_CODES.GONE,
  413: ERROR_CODES.PAYLOAD_TOO_LARGE_HTTP,
  414: ERROR_CODES.URI_TOO_LONG,
  415: ERROR_CODES.UNSUPPORTED_MEDIA_TYPE,
  422: ERROR_CODES.UNPROCESSABLE_ENTITY,
  429: ERROR_CODES.TOO_MANY_REQUESTS,
  500: ERROR_CODES.INTERNAL_SERVER_ERROR,
  501: ERROR_CODES.NOT_IMPLEMENTED,
  502: ERROR_CODES.BAD_GATEWAY,
  503: ERROR_CODES.SERVICE_UNAVAILABLE,
  504: ERROR_CODES.GATEWAY_TIMEOUT,
  505: ERROR_CODES.HTTP_VERSION_NOT_SUPPORTED
};

/**
 * 錯誤代碼對應的 HTTP 狀態碼映射
 */
export const ERROR_CODE_TO_HTTP_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.UNKNOWN_ERROR]: 500,
  [ERROR_CODES.INTERNAL_ERROR]: 500,

  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.INVALID_EMAIL]: 400,
  [ERROR_CODES.INVALID_PASSWORD]: 400,
  [ERROR_CODES.INVALID_PHONE]: 400,
  [ERROR_CODES.INVALID_DATE]: 400,
  [ERROR_CODES.INVALID_NUMBER]: 400,
  [ERROR_CODES.INVALID_RANGE]: 400,
  [ERROR_CODES.DUPLICATE_VALUE]: 409,
  [ERROR_CODES.FIELD_TOO_SHORT]: 400,
  [ERROR_CODES.FIELD_TOO_LONG]: 400,
  [ERROR_CODES.VALUE_TOO_SMALL]: 400,
  [ERROR_CODES.VALUE_TOO_LARGE]: 400,

  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.ACCOUNT_NOT_FOUND]: 404,
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: 404,
  [ERROR_CODES.CONTRACT_NOT_FOUND]: 404,
  [ERROR_CODES.CUSTOMER_NOT_FOUND]: 404,
  [ERROR_CODES.PRINCIPAL_NOT_FOUND]: 404,
  [ERROR_CODES.DOCUMENT_NOT_FOUND]: 404,
  [ERROR_CODES.FILE_NOT_FOUND]: 404,
  [ERROR_CODES.REPORT_NOT_FOUND]: 404,

  [ERROR_CODES.APPLICATION_ERROR]: 500,
  [ERROR_CODES.BUSINESS_LOGIC_ERROR]: 422,
  [ERROR_CODES.OPERATION_FAILED]: 500,
  [ERROR_CODES.CREATE_FAILED]: 500,
  [ERROR_CODES.UPDATE_FAILED]: 500,
  [ERROR_CODES.DELETE_FAILED]: 500,
  [ERROR_CODES.SAVE_FAILED]: 500,
  [ERROR_CODES.LOAD_FAILED]: 500,
  [ERROR_CODES.SEARCH_FAILED]: 500,
  [ERROR_CODES.EXPORT_FAILED]: 500,
  [ERROR_CODES.IMPORT_FAILED]: 500,
  [ERROR_CODES.PROCESS_FAILED]: 500,
  [ERROR_CODES.INVALID_STATE]: 422,
  [ERROR_CODES.CONCURRENCY_CONFLICT]: 409,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,

  [ERROR_CODES.REPOSITORY_ERROR]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.CONNECTION_ERROR]: 503,
  [ERROR_CODES.QUERY_ERROR]: 500,
  [ERROR_CODES.TRANSACTION_ERROR]: 500,
  [ERROR_CODES.CONSTRAINT_VIOLATION]: 422,
  [ERROR_CODES.DUPLICATE_KEY]: 409,
  [ERROR_CODES.FOREIGN_KEY_VIOLATION]: 422,
  [ERROR_CODES.DATA_INTEGRITY_ERROR]: 422,
  [ERROR_CODES.TIMEOUT_ERROR]: 408,

  [ERROR_CODES.AUTHENTICATION_ERROR]: 401,
  [ERROR_CODES.LOGIN_FAILED]: 401,
  [ERROR_CODES.LOGOUT_FAILED]: 500,
  [ERROR_CODES.REGISTRATION_FAILED]: 400,
  [ERROR_CODES.PASSWORD_RESET_FAILED]: 500,
  [ERROR_CODES.PASSWORD_CHANGE_FAILED]: 400,
  [ERROR_CODES.ACCOUNT_NOT_EXISTS]: 404,
  [ERROR_CODES.ACCOUNT_EXISTS]: 409,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.ACCOUNT_LOCKED]: 423,
  [ERROR_CODES.ACCOUNT_DISABLED]: 403,
  [ERROR_CODES.ACCOUNT_NOT_VERIFIED]: 403,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
  [ERROR_CODES.PHONE_NOT_VERIFIED]: 403,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.ACCESS_TOKEN_INVALID]: 401,
  [ERROR_CODES.REFRESH_TOKEN_INVALID]: 401,
  [ERROR_CODES.RESET_TOKEN_INVALID]: 401,
  [ERROR_CODES.SESSION_EXPIRED]: 401,
  [ERROR_CODES.TWO_FACTOR_REQUIRED]: 401,
  [ERROR_CODES.TWO_FACTOR_FAILED]: 401,
  [ERROR_CODES.OAUTH_FAILED]: 401,

  [ERROR_CODES.NETWORK_ERROR]: 503,
  [ERROR_CODES.HTTP_ERROR]: 500,
  [ERROR_CODES.CONNECTION_FAILED]: 503,
  [ERROR_CODES.REQUEST_TIMEOUT]: 408,
  [ERROR_CODES.OFFLINE_ERROR]: 503,
  [ERROR_CODES.CORS_ERROR]: 403,
  [ERROR_CODES.SSL_ERROR]: 495,
  [ERROR_CODES.DNS_ERROR]: 503,
  [ERROR_CODES.REQUEST_ABORTED]: 499,
  [ERROR_CODES.PAYLOAD_TOO_LARGE]: 413,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,

  [ERROR_CODES.BAD_REQUEST]: 400,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND_HTTP]: 404,
  [ERROR_CODES.METHOD_NOT_ALLOWED]: 405,
  [ERROR_CODES.REQUEST_TIMEOUT_HTTP]: 408,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.GONE]: 410,
  [ERROR_CODES.PAYLOAD_TOO_LARGE_HTTP]: 413,
  [ERROR_CODES.URI_TOO_LONG]: 414,
  [ERROR_CODES.UNSUPPORTED_MEDIA_TYPE]: 415,
  [ERROR_CODES.UNPROCESSABLE_ENTITY]: 422,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.NOT_IMPLEMENTED]: 501,
  [ERROR_CODES.BAD_GATEWAY]: 502,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.GATEWAY_TIMEOUT]: 504,
  [ERROR_CODES.HTTP_VERSION_NOT_SUPPORTED]: 505,

  [ERROR_CODES.INSUFFICIENT_BALANCE]: 422,
  [ERROR_CODES.ACCOUNT_FROZEN]: 423,
  [ERROR_CODES.TRANSACTION_LIMIT_EXCEEDED]: 422,
  [ERROR_CODES.INVALID_TRANSACTION_TYPE]: 400,
  [ERROR_CODES.INVALID_TRANSACTION_STATUS]: 400,
  [ERROR_CODES.TRANSACTION_ALREADY_PROCESSED]: 409,
  [ERROR_CODES.CONTRACT_EXPIRED]: 410,
  [ERROR_CODES.CONTRACT_NOT_ACTIVE]: 422,
  [ERROR_CODES.CONTRACT_ALREADY_SIGNED]: 409,
  [ERROR_CODES.CUSTOMER_INACTIVE]: 422,
  [ERROR_CODES.PRINCIPAL_INACTIVE]: 422,
  [ERROR_CODES.DOCUMENT_LOCKED]: 423,
  [ERROR_CODES.FILE_TOO_LARGE]: 413,
  [ERROR_CODES.UNSUPPORTED_FILE_TYPE]: 415,
  [ERROR_CODES.REPORT_GENERATION_FAILED]: 500,

  [ERROR_CODES.CONFIGURATION_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE_ERROR]: 503,
  [ERROR_CODES.MAINTENANCE_MODE]: 503,
  [ERROR_CODES.FEATURE_DISABLED]: 501,
  [ERROR_CODES.QUOTA_EXCEEDED]: 429,
  [ERROR_CODES.RESOURCE_EXHAUSTED]: 429,
  [ERROR_CODES.DEPENDENCY_UNAVAILABLE]: 503
};
